/*
 This file is generated and updated by Sencha Cmd. You can edit this file as
 needed for your application, but these edits will have to be merged by
 Sencha Cmd when upgrading.
 */

/* global Ext */

// DO NOT DELETE - this directive is required for Sencha Cmd packages to work. 
//@require @packageOverrides
if (Ext.repoDevMode) {
    document.write('<link rel="stylesheet" type="text/css" href="../build/testextjs/ext-theme-' +
            Ext.themeName + '/resources/testextjs-all.css"/>');
}
//Ext.Loader.setPath('Ext.ux', 'extjs/ux');  
Ext.application({
    name: 'testextjs',
    requires: [
        'Ext.util.History',
        'testextjs.view.Header',
        'testextjs.view.Navigation',
        'testextjs.view.Main',
        'testextjs.view.window.BasicWindow',
        'testextjs.view.sm_user.user.UserManager',
        'testextjs.view.sm_user.role.RoleManager',
        'testextjs.view.sm_user.role.action.add',
        'testextjs.view.sm_user.role.action.addPrivilegeBis',
        'testextjs.view.sm_user.privilege.PrivilegeManager',
        'testextjs.view.sm_user.module.ModuleManager',
        'testextjs.view.sm_user.menu.MenuManager',
        'testextjs.view.sm_user.sous_menu.SousmenuManager',
        'testextjs.view.sm_user.menu.action.add',
        'testextjs.view.sm_user.sous_menu.action.add',
        'testextjs.model.Role',
        'testextjs.model.Utilisateur',
        'testextjs.view.sm_user.user.action.addpwd',
        'testextjs.view.sm_user.user.action.add',
        'testextjs.store.Statut',
        'testextjs.model.Statut',
        'testextjs.view.sm_user.user.action.addpwd',
        'testextjs.view.sm_user.user.action.add',
        'testextjs.view.sm_user.skin.SkinManager',
        'testextjs.view.sm_user.skin.action.add',
        'testextjs.view.sm_user.language.action.add',
        'testextjs.view.sm_user.language.LanguageManager',
        'testextjs.model.dd.Simple',
        'testextjs.view.sm_user.role.action.addPrivilege',
        'testextjs.view.sm_user.role.action.addPrivilegeItem',
        'testextjs.model.Notification',
        'testextjs.view.sm_user.notification.NotificationManager',
        'testextjs.view.sm_user.myaccount.MyaccountManager',
        'testextjs.view.sm_user.about.AboutManager',
        'testextjs.model.UserPhone',
        'testextjs.view.sm_user.user_phone.action.add',
        'testextjs.view.sm_user.user_phone.UserphoneManager',
        'testextjs.view.sm_user.alertevent.AlerteventManager',
        'testextjs.model.Alertevent',
        'testextjs.view.sm_user.alertevent.action.add',
        'testextjs.view.sm_user.alertevent.action.adduserphonealertevent',
        'testextjs.model.Userphonealertevent',
        'testextjs.view.sm_user.alertevent.action.adduserphonetoalert',
        'testextjs.model.Outboudmessage',
        'testextjs.view.sm_user.outboudmessage.OutboudmessageManager',
        'testextjs.model.Preenregistrement',
        'testextjs.view.sm_user.role.RoleManager',
        'testextjs.view.sm_user.privilege.PrivilegeManager',
        'testextjs.view.sm_user.module.ModuleManager',
        'testextjs.view.sm_user.menu.MenuManager',
        'testextjs.view.sm_user.sous_menu.SousmenuManager',
        'testextjs.view.sm_user.menu.action.add',
        'testextjs.view.sm_user.sous_menu.action.add',
        'testextjs.model.Role',
        'testextjs.model.Utilisateur',
        'testextjs.view.sm_user.user.action.addpwd',
        'testextjs.view.sm_user.user.action.add',
        'testextjs.store.Statut',
        'testextjs.model.Statut',
        'testextjs.view.sm_user.user.action.addpwd',
        'testextjs.view.sm_user.user.action.add',
        'testextjs.view.sm_user.skin.SkinManager',
        'testextjs.view.sm_user.skin.action.add',
        'testextjs.view.sm_user.language.action.add',
        'testextjs.view.sm_user.language.LanguageManager',
        'testextjs.model.dd.Simple',
        'testextjs.view.sm_user.role.action.addPrivilege',
        'testextjs.view.sm_user.role.action.addPrivilegeItem',
        'testextjs.model.Notification',
        'testextjs.view.sm_user.notification.NotificationManager',
        'testextjs.view.sm_user.myaccount.MyaccountManager',
        'testextjs.view.sm_user.about.AboutManager',
        'testextjs.model.Preenregistrement',
        'testextjs.view.sm_user.detailsvente.DetailsVenteManager',
        'testextjs.model.DetailsVente',
        'testextjs.view.sm_user.detailsvente.action.add',
//
//
//
//        //groupefamille
        'testextjs.model.GroupeFamille',
        'testextjs.view.configmanagement.groupefamille.GroupeFamilleManager',
        'testextjs.view.configmanagement.groupefamille.action.add',
        'Ext.util.History',
        'testextjs.view.Header',
        'testextjs.view.Navigation',
        'testextjs.view.Main',
        'testextjs.view.window.BasicWindow',
        'testextjs.view.sm_user.user.UserManager',
        'testextjs.view.sm_user.role.RoleManager',
        'testextjs.view.sm_user.privilege.PrivilegeManager',
        'testextjs.view.sm_user.module.ModuleManager',
        'testextjs.view.sm_user.menu.MenuManager',
        'testextjs.view.sm_user.sous_menu.SousmenuManager',
        'testextjs.view.sm_user.menu.action.add',
        'testextjs.view.sm_user.sous_menu.action.add',
        'testextjs.model.Role',
        'testextjs.model.Utilisateur',
        'testextjs.view.sm_user.user.action.addpwd',
        'testextjs.view.sm_user.user.action.add',
        'testextjs.store.Statut',
        'testextjs.model.Statut',
        'testextjs.view.sm_user.user.action.addpwd',
        'testextjs.view.sm_user.user.action.add',
        'testextjs.view.sm_user.skin.SkinManager',
        'testextjs.view.sm_user.skin.action.add',
        'testextjs.view.sm_user.language.action.add',
        'testextjs.view.sm_user.language.LanguageManager',
        'testextjs.model.dd.Simple',
        'testextjs.view.sm_user.role.action.addPrivilege',
        'testextjs.view.sm_user.role.action.addPrivilegeItem',
        'testextjs.model.Notification',
        'testextjs.view.sm_user.notification.NotificationManager',
        'testextjs.view.sm_user.myaccount.MyaccountManager',
        'testextjs.view.sm_user.about.AboutManager',
        'testextjs.model.Preenregistrement',
        'testextjs.view.sm_user.dovente.action.displayAyantDroit',

//
//        //famille
        'testextjs.model.Famille',
        'testextjs.view.configmanagement.famille.FamilleManager',

        'testextjs.view.configmanagement.famille.action.add',
        'testextjs.view.configmanagement.famille.action.maxVente',
        'testextjs.model.StatVenteFamille',
        //optimisation quantité
        'testextjs.model.OptimisationQuantite',
        'testextjs.view.configmanagement.optimisationquantite.OptimisationQuantiteManager',
        'testextjs.view.configmanagement.optimisationquantite.action.add',
        //code gestion
        'testextjs.model.CodeGestion',
        'testextjs.view.configmanagement.codegestion.CodeGestionManager',
        'testextjs.view.configmanagement.codegestion.action.add',
        //code contre indication
        'testextjs.model.ContreIndication',
        'testextjs.view.configmanagement.contreindication.ContreIndicationManager',
        'testextjs.view.configmanagement.contreindication.action.add',
        //tranche
        'testextjs.model.Tranche',
        'testextjs.view.configmanagement.tranche.TrancheManager',
        'testextjs.view.configmanagement.tranche.action.add',
        //type societe
        'testextjs.model.TypeSociete',
        'testextjs.view.configmanagement.typesociete.TypeSocieteManager',
        'testextjs.view.configmanagement.tranche.action.add',
        //type remise
        'testextjs.model.TypeRemise',
        'testextjs.view.configmanagement.typeremise.TypeRemiseManager',
        'testextjs.view.configmanagement.typeremise.action.add',
        //Categorie ayant droit
        'testextjs.model.CategorieAyantdroit',
        'testextjs.view.configmanagement.categorieayantdroit.CategorieAyantdroitManager',
        'testextjs.view.configmanagement.categorieayantdroit.action.add',
        //Categorie Dossier tiers payant
        'testextjs.model.DossierTiersPayant',
        'testextjs.view.configmanagement.dossiertierspayant.DossierTiersPayantManager',
        'testextjs.view.configmanagement.dossiertierspayant.action.add',
        //Escompte Societe
        'testextjs.model.EscompteSociete',
        'testextjs.view.configmanagement.escomptesociete.EscompteSocieteManager',
        'testextjs.view.configmanagement.escomptesociete.action.add',
        //ville
        'testextjs.model.Ville',
        'testextjs.view.configmanagement.ville.VilleManager',
        'testextjs.view.configmanagement.ville.action.add',
        //grossiste
        'testextjs.model.Grossiste',
        'testextjs.view.configmanagement.grossiste.GrossisteManager',
        'testextjs.view.configmanagement.grossiste.action.add',
        //remise
        'testextjs.model.Remise',
        'testextjs.view.configmanagement.remise.RemiseManager',
        'testextjs.view.configmanagement.remise.action.add',
        //risque
        'testextjs.model.Risque',
        'testextjs.view.configmanagement.risque.RisqueManager',
        'testextjs.view.configmanagement.risque.action.add',
        //Type risque
        'testextjs.model.Typerisque',
        'testextjs.view.configmanagement.typerisque.TyperisqueManager',
        'testextjs.view.configmanagement.typerisque.action.add',
        //Regime caisse
        'testextjs.model.Regimecaisse',
        'testextjs.view.configmanagement.regimecaisse.RegimecaisseManager',
        'testextjs.view.configmanagement.regimecaisse.action.add',
        // Medecin
        'testextjs.model.Medecin',
        'testextjs.view.configmanagement.medecin.MedecinManager',
        'testextjs.view.configmanagement.medecin.action.add',
        // type tiers payant
        'testextjs.model.TypeTiersPayant',
        'testextjs.view.tierspayantmanagement.typetierspayant.TypeTiersPayantManager',
        'testextjs.view.tierspayantmanagement.typetierspayant.action.add',
        'testextjs.view.tierspayantmanagement.tierspayant.action.addPhoto',
        // tiers payant
        'testextjs.model.TiersPayant',
        'testextjs.view.tierspayantmanagement.tierspayant.TiersPayantManager',
        'testextjs.view.tierspayantmanagement.tierspayant.action.add',
        'testextjs.view.tierspayantmanagement.balanceagee_detail.action.detailTransactionClient',
        'testextjs.view.tierspayantmanagement.balanceagee_detail.BalanceageeRecapitulatifDetailManager',
        'testextjs.view.tierspayantmanagement.balanceagee.BalanceageeManager',
        // client
        'testextjs.model.Client',
        'testextjs.view.configmanagement.client.action.add',
        'testextjs.view.configmanagement.client.ClientManager',
        'testextjs.view.sm_user.client.ClientManager',
        'testextjs.view.sm_user.mainmenu.MainMenuManager',
        'testextjs.view.configmanagement.client.action.addmedecin',

        'testextjs.model.Warehouse',
        'testextjs.view.sm_user.entreestock.EntreestockManager',
        'testextjs.view.sm_user.entreestock.action.add',
        // Etat du stock
        'testextjs.model.Productitemstock',
        'testextjs.view.sm_user.etatstock.EtatstockManager',

// Caisse

        'testextjs.view.sm_user.coffrecaisse.CoffrecaisseManager',
        'testextjs.view.sm_user.ouverturecaisse.OuverturecaisseManager',
        'testextjs.model.Ouverturecaisse',
        'testextjs.model.Caisse',
        'testextjs.view.sm_user.caisse.CaisseManager',
        // 'testextjs.model.Caisse',
        'testextjs.model.ResumeCaisse',

        //  'testextjs.model.ResumeCaisse'


        // Gerer Famille Order
        'testextjs.model.Familleorder',
        'testextjs.view.sm_user.familleorder.FamilleOrderManager',
        'testextjs.view.sm_user.familleorder.action.add',
        // Gerer Famille Order
        'testextjs.model.Warehouseorder',
        'testextjs.view.sm_user.warehouseorder.WarehouseOrderManager',
        // preenregistrementcompteclient
        'testextjs.model.Preenregistrementcompteclient',
        'testextjs.view.sm_user.preenregistrementcompteclient.PreenregistrementcompteclientManager',
        // preenregistrementcompteclienttierspayant
        'testextjs.model.Preenregistrementcompteclienttierspayant',
        'testextjs.view.sm_user.preenregistrementcompteclienttierspayant.PreenregistrementcompteclienttierspayantManager',
        'testextjs.model.TypeVente',
        'testextjs.view.sm_user.dovente.action.addclt',
        'testextjs.view.sm_user.dovente.action.addtp',
        'testextjs.view.sm_user.dovente.action.addTiersPayant',
        'testextjs.view.sm_user.dovente.action.addTiersPayantItem',
        'testextjs.model.VPropositionCde',
        'testextjs.model.CodeGestion',
        'testextjs.model.CodeActe',
        'testextjs.model.ZoneGeographique',
        'testextjs.view.configmanagement.client.action.infoCompte',

        'testextjs.model.EscompteSocieteTranche',
        //retrocession
        'testextjs.view.sm_user.retrocession.retrocessionManager',
        'testextjs.model.Retrocession',

        'testextjs.model.DetailsVenteRetrocession',
        'testextjs.model.Tva',
        'testextjs.view.sm_user.doventeretrocession.ShowDetailRetrocessionManager',
        // Gerer Famille Order
        'testextjs.model.Familleorder',
        'testextjs.view.sm_user.familleorder.FamilleOrderManager',
        'testextjs.view.sm_user.familleorder.action.add',
        // Gerer Famille Order
        'testextjs.model.Warehouseorder',
        'testextjs.view.sm_user.warehouseorder.WarehouseOrderManager',
        // preenregistrementcompteclient
        'testextjs.model.Preenregistrementcompteclient',
        'testextjs.view.sm_user.preenregistrementcompteclient.PreenregistrementcompteclientManager',
        // preenregistrementcompteclienttierspayant
        'testextjs.model.Preenregistrementcompteclienttierspayant',
        'testextjs.view.sm_user.preenregistrementcompteclienttierspayant.PreenregistrementcompteclienttierspayantManager',
        'testextjs.model.TypeVente',
        'testextjs.view.sm_user.dovente.action.addclt',
        'testextjs.view.sm_user.dovente.action.addtp',
        'testextjs.view.sm_user.dovente.action.addTiersPayant',
        'testextjs.view.sm_user.dovente.action.addTiersPayantItem',
        'testextjs.model.VPropositionCde',
        'testextjs.model.CodeGestion',
        'testextjs.model.CodeActe',
        'testextjs.model.ZoneGeographique',
        'testextjs.view.configmanagement.client.action.infoCompte',
        // 'testextjs.view.sm_user.contregisterorder.ContregisterorderManager'
        'testextjs.view.sm_user.retrocession.retrocessionManager',
        'testextjs.model.Retrocession',
        'testextjs.view.sm_user.doventeretrocession.DoventeRetrocessionManager',

        // Famille
        'testextjs.view.configmanagement.famillearticle.action.add',
        'testextjs.view.configmanagement.famille.action.addfamillegrossiste',
        'testextjs.model.FamilleArticle',
        'testextjs.view.configmanagement.famillearticle.FamilleArticleManager',
        'testextjs.model.FamilleGrossiste',
        'testextjs.view.configmanagement.famille.action.addgrossiste',
        // Zone Geo 
        'testextjs.model.ZoneGeographique',
        'testextjs.view.configmanagement.zonegeographique.ZoneGeographiqueManager',
        'testextjs.view.configmanagement.zonegeographique.action.add',
        // Representant grossiste
        'testextjs.model.Representantgrossiste',
        'testextjs.view.configmanagement.representantgrossiste.RepresentantGrossisteManager',
        'testextjs.view.configmanagement.representantgrossiste.action.add',
        // Ayant Droit
        'testextjs.model.AyantDroit',
        'testextjs.view.configmanagement.ayantdroit.AyantDroitManager',
        'testextjs.view.configmanagement.ayantdroit.action.add',
        'testextjs.view.configmanagement.client.action.addcltayantdroit',
        'testextjs.view.configmanagement.client.action.showclttierspayant',
        'testextjs.view.configmanagement.compteclient.action.addclttierspayant',
//        'testextjs.view.configmanagement.client.action.addComptecltTierpayant',
//        'testextjs.view.configmanagement.client.action.addComptecltTierpayantItem',
        // Grille Remise

        //retrocession
        'testextjs.view.sm_user.retrocession.retrocessionManager',
        'testextjs.model.Retrocession',

        'testextjs.model.DetailsVenteRetrocession',
        'testextjs.model.Tva',

        'testextjs.view.sm_user.retrocession.action.addClient',
        'testextjs.view.sm_user.retrocession.ConfrereManager',
        // Gerer Famille Order
        'testextjs.model.Familleorder',
        'testextjs.view.sm_user.familleorder.FamilleOrderManager',
        'testextjs.view.sm_user.familleorder.action.add',
        // Gerer Famille Order
        'testextjs.model.Warehouseorder',
        'testextjs.view.sm_user.warehouseorder.WarehouseOrderManager',
        // preenregistrementcompteclient
        'testextjs.model.Preenregistrementcompteclient',
        'testextjs.view.sm_user.preenregistrementcompteclient.PreenregistrementcompteclientManager',
        // preenregistrementcompteclienttierspayant
        'testextjs.model.Preenregistrementcompteclienttierspayant',
        'testextjs.view.sm_user.preenregistrementcompteclienttierspayant.PreenregistrementcompteclienttierspayantManager',
        'testextjs.model.TypeVente',
        'testextjs.view.sm_user.dovente.action.addclt',
        'testextjs.view.sm_user.dovente.action.addtp',
        'testextjs.view.sm_user.dovente.action.addTiersPayant',
        'testextjs.view.sm_user.dovente.action.addTiersPayantItem',
        'testextjs.model.VPropositionCde',
        'testextjs.model.CodeGestion',
        'testextjs.model.CodeActe',
        'testextjs.model.ZoneGeographique',
        'testextjs.view.configmanagement.client.action.infoCompte',
        // 'testextjs.view.sm_user.contregisterorder.ContregisterorderManager'
        'testextjs.view.sm_user.retrocession.retrocessionManager',
        'testextjs.model.Retrocession',

        // Famille
        'testextjs.view.configmanagement.famillearticle.action.add',
        'testextjs.model.FamilleArticle',
        'testextjs.view.configmanagement.famillearticle.FamilleArticleManager',
        'testextjs.view.configmanagement.famille.action.detailArticle',
        // Zone Geo 
        'testextjs.model.ZoneGeographique',
        'testextjs.view.configmanagement.zonegeographique.ZoneGeographiqueManager',
        'testextjs.view.configmanagement.zonegeographique.action.add',
        // Representant grossiste
        'testextjs.model.Representantgrossiste',
        'testextjs.view.configmanagement.representantgrossiste.RepresentantGrossisteManager',
        'testextjs.view.configmanagement.representantgrossiste.action.add',
        // Ayant Droit
        'testextjs.model.AyantDroit',
        'testextjs.view.configmanagement.ayantdroit.AyantDroitManager',
        'testextjs.view.configmanagement.ayantdroit.action.add',
        'testextjs.view.configmanagement.client.action.addcltayantdroit',
        'testextjs.view.configmanagement.client.action.showclttierspayant',
        'testextjs.view.configmanagement.compteclient.action.addclttierspayant',
//        'testextjs.view.configmanagement.client.action.addComptecltTierpayant',
//        'testextjs.view.configmanagement.client.action.addComptecltTierpayantItem',
        // Grille Remise

        'testextjs.model.GrilleRemise',
        'testextjs.view.configmanagement.grilleremise.GrilleRemiseManager',
        'testextjs.view.configmanagement.grilleremise.action.add',
        //facturation tiers payant
        'testextjs.model.FacturationClientTierspayant',
        'testextjs.view.tierspayantmanagement.facturationtierspayant.FacturationTiersPayantManager',
        'testextjs.view.tierspayantmanagement.facturationtierspayant.action.detailTransactionClient',
        'testextjs.model.GrilleRemise',
        'testextjs.view.configmanagement.grilleremise.GrilleRemiseManager',
        'testextjs.view.configmanagement.grilleremise.action.add',
        //gestion de stock
        'testextjs.model.FamilleStock',
        'testextjs.view.stockmanagement.etatstock.EtatStockManager',
        'testextjs.view.stockmanagement.etatstock.action.add',
        'testextjs.view.stockmanagement.suivistockvente.SuiviStockVenteManager',
        'testextjs.view.stockmanagement.perime.PerimeManager',
        'testextjs.view.stockmanagement.suivistockvente.EvaluationVenteMoyenneManager',
        'testextjs.view.stockmanagement.suivistockvente.SuiviDetailStockVenteManager',
        'testextjs.view.stockmanagement.etatstock.action.editjourvente',
        // 
        'testextjs.model.GrilleRemise',
        'testextjs.model.Workflowremisearticle',
        'testextjs.view.configmanagement.workflowremisearticle.WorkflowremisearticleManager',
        'testextjs.view.configmanagement.workflowremisearticle.action.add',
        // GESTION DES COMMANDES
        'testextjs.model.RuptureFournisseur',
        'testextjs.view.commandemanagement.rupturefournisseur.RuptureFournisseurManager',
        'testextjs.view.commandemanagement.etats.EtatControleManager',
        'testextjs.model.EtatControle',
        'testextjs.view.configmanagement.grossiste.action.grossisteview',
        'testextjs.view.commandemanagement.order.action.manageorderpass',
        'testextjs.view.commandemanagement.order.action.editgrossiste',
        'testextjs.view.commandemanagement.bonlivraison.action.editprice',
        'testextjs.view.commandemanagement.retourfournisseur.retourFrsManager',
        'testextjs.view.commandemanagement.retourfournisseur.action.add',
        'testextjs.model.RetourFournisseur',
        'testextjs.model.RetourFournisseurDetail',
        'testextjs.view.configmanagement.motifretour.MotifRetourManager',
        'testextjs.model.MotifRetour',
        'testextjs.view.configmanagement.motifretour.action.add',
        'testextjs.view.commandemanagement.cmde_passees.action.add',
        'testextjs.model.BonLivraison',
        'testextjs.view.commandemanagement.suggestion.SuggestionManager',
        'testextjs.model.Suggestion',
        'testextjs.model.SuggestionOrder',
        'testextjs.model.Order',
        'testextjs.view.commandemanagement.bonlivraison.action.add',
        'testextjs.view.commandemanagement.order.OrderManager',
        'testextjs.view.commandemanagement.order.action.add',
        'testextjs.model.TSuggestionOrderDetails',
        'testextjs.model.OrderDetail',
        'testextjs.view.commandemanagement.suivi_order.SuiviOrderManager',
        'testextjs.view.sm_user.suggerercde.SuggerercdeManager',
        'testextjs.view.commandemanagement.suggestions_commandees.suggestionsCommandeesManager',
        'testextjs.view.commandemanagement.suggestion.Suggestion_Manager',
        'testextjs.view.commandemanagement.suivi_order.action.add',
        'testextjs.view.commandemanagement.bonlivraison.BonLivraisonManager',
        //  Fiche Societe
        'testextjs.model.FicheSociete',
        'testextjs.view.configmanagement.fichesociete.FicheSocieteManager',
        'testextjs.view.configmanagement.ville.VilleManager',
        'testextjs.view.configmanagement.escomptesociete.EscompteSocieteManager',
        'testextjs.view.configmanagement.fichesociete.action.add',
        'testextjs.view.configmanagement.fichesociete.action.add',

        'testextjs.model.Balance',
        //lot article
        'testextjs.view.configmanagement.lotarticle.LotManager',
        'testextjs.model.Lot',
        'testextjs.view.configmanagement.lotarticle.action.add',
        //Tableau
        'testextjs.view.configmanagement.tableau.TableauManager',
        'testextjs.model.Tableau',
        'testextjs.view.configmanagement.tableau.action.add',
        //DCI      
        'testextjs.view.configmanagement.dci.DciManager',
        'testextjs.model.Dci',
        'testextjs.view.configmanagement.dci.action.add',
        //Etiquette      
        // 'testextjs.view.configmanagement.etiquette.EtiquetteManager',
        'testextjs.model.Etiquette',
        //'testextjs.view.configmanagement.etiquette.action.add',
        //Taux de Marque
        'testextjs.view.configmanagement.tauxmarque.TauxmarqueManager',
        'testextjs.model.TauxMarque',
        'testextjs.view.configmanagement.tauxmarque.action.add',
        'testextjs.view.sm_user.journalvente.JournalventeManager',
        'testextjs.model.Cashtransactiondata',

        //Forme Article
        'testextjs.model.Formearticle',
        'testextjs.view.configmanagement.formearticle.action.add',
        'testextjs.view.configmanagement.formearticle.FormeArticleManager',
        // Fabricant
        'testextjs.model.Fabriquant',
        'testextjs.view.configmanagement.fabriquant.action.add',
        'testextjs.view.configmanagement.fabriquant.FabricantManager',
        // Etat Article
        'testextjs.model.EtatArticle',
        'testextjs.view.configmanagement.etatarticle.action.add',
        'testextjs.view.configmanagement.etatarticle.EtatArticleManager',
        //Taux de Rembourssement
        'testextjs.model.Tauxrembourssement',
        'testextjs.view.configmanagement.tauxrembourssement.action.add',
        'testextjs.view.configmanagement.tauxrembourssement.TauxrembourssementManager',
        // WIZARD ARTICLE
        'testextjs.view.configmanagement.famille.action.infogenerale',
        'testextjs.view.configmanagement.famille.action.comptabilite',
        'testextjs.view.configmanagement.famille.action.WizardForm',
        'testextjs.view.configmanagement.famille.action.autreinfos',
        // Specialite Medecin        
        'testextjs.model.Specialite',
        'testextjs.view.configmanagement.specialite.action.add',
        'testextjs.view.configmanagement.specialite.SpecialiteManager',
        //gestion des etiquettes
        'testextjs.model.Typeetiquette',
        'testextjs.view.stockmanagement.etiquette.EtiquetteManager',
        'testextjs.view.stockmanagement.etiquette.EtiquetteManager',
        'testextjs.view.stockmanagement.etiquette.action.printEtiquette',
        //gestion des inventaires
        'testextjs.view.stockmanagement.inventaire.InventaireManager',
        'testextjs.view.stockmanagement.inventaire.action.add',
        'testextjs.view.stockmanagement.inventaire.action.addBis',
        'testextjs.model.Inventaire',
        'testextjs.view.stockmanagement.inventaire.action.addArticle',
        'testextjs.view.stockmanagement.inventaire.action.editInventaireManager',
        'testextjs.view.stockmanagement.inventaire.action.detailInventaireManager',
        'testextjs.view.stockmanagement.inventaire.EcartInventaireManager',
        // Numero Caisse

        'testextjs.model.NumeroCaisse',
        'testextjs.view.configmanagement.numerocaisse.action.add',
        'testextjs.view.configmanagement.numerocaisse.NumeroCaisseManager',
        'testextjs.model.NumeroCaisse',
        'testextjs.view.configmanagement.numerocaisse.action.add',
        'testextjs.view.configmanagement.numerocaisse.NumeroCaisseManager',
        'testextjs.view.commandemanagement.cmde_passees.OrderPassManager',
        'testextjs.view.commandemanagement.cmde_passees.action.livraison',
        'testextjs.model.CentrePayeur',
        'testextjs.view.configmanagement.centrepayeur.action.add',
        'testextjs.view.configmanagement.centrepayeur.CentrePayeurManager',
        'testextjs.view.configmanagement.client.action.addMedecinClientItem',
        'testextjs.view.configmanagement.client.action.addMedecinClient',
        'testextjs.view.stockmanagement.perime.action.addDatePeromption',
        //gestion reserve
        'testextjs.view.stockmanagement.reserve.ReserveManager',
        'testextjs.view.stockmanagement.reserve.action.add',
        'testextjs.view.stockmanagement.reserve.action.addToReserve',
        'testextjs.view.sm_user.diffclient.DiffManager',
        'testextjs.model.Differes',
        //gestion des depots

        'testextjs.view.stockmanagement.dodepot.action.addclt',
        'testextjs.view.stockmanagement.stockdepot.StockDepotManager',
        'testextjs.view.stockmanagement.stockdepot.action.add',
        'testextjs.view.stockmanagement.dodepot.action.add',
        //gestion des deconditionnements
        'testextjs.view.configmanagement.famille.action.doDecondition',
        'testextjs.model.ModeReglement',
        'testextjs.view.sm_user.dovente.action.checkdif',
        'testextjs.view.sm_user.dovente.action.PayDebt',
        'testextjs.view.sm_user.dovente.action.displayArticle',
        'testextjs.view.sm_user.dovente.action.updateQuantity',
        'testextjs.view.sm_user.dovente.action.displayCustomer',
        'testextjs.view.sm_user.dovente.action.addAyant',
        'testextjs.model.Company',
        //gestion des lititges
        'testextjs.model.TypeLitige',
        'testextjs.model.Litige',
        'testextjs.view.configmanagement.litige.LitigeManager',
        'testextjs.view.configmanagement.litige.action.detailTransactionLitige',
        'testextjs.view.configmanagement.litige.action.add',
        'testextjs.view.configmanagement.litige.action.detailLitige',
        //balange agée
        'testextjs.view.tierspayantmanagement.balanceagee_detail.BalanceageeDetailManager',
        'testextjs.view.configmanagement.client.action.addClient',
        'testextjs.view.stockmanagement.etiquette.action.add',
        'testextjs.view.stockmanagement.etiquette.action.add',
        'testextjs.view.stockmanagement.perime.PerimeRemoveToStockManager',
        'testextjs.view.stockmanagement.perime.action.add',
        //facturation
        'testextjs.model.Facture',
        'testextjs.model.DetailFacture',
        'testextjs.model.DossierFacture',
        'testextjs.model.Bordereau',
        'testextjs.view.sm_user.editfacture.action.detailTransactionTiersPayant',
        'testextjs.view.sm_user.editfacture.action.detailTransactionFournisseur',
        'testextjs.view.sm_user.editfacture.EditFactureManager',
        'testextjs.view.sm_user.editfacture.action.add',
        'testextjs.model.TypeFacture',
        'testextjs.view.sm_user.editfacture.action.DetailFacture',
        'testextjs.view.sm_user.editbordereau.EditBordereaumanager',
        'testextjs.view.sm_user.editbordereau.action.add',
        'testextjs.view.sm_user.editfacture.action.DetailFactureFournisseur',
        'testextjs.view.sm_user.diffclient.action.BuyDiffere',
        'testextjs.view.sm_user.reglement.ReglementManager',
        'testextjs.view.sm_user.reglement.action.DoReglement',
        'testextjs.view.sm_user.reglement.action.displayDossier',
        'testextjs.view.sm_user.reglement.action.displayBordereau',
        'testextjs.view.sm_user.editfacture.action.DetaillBon',
        'testextjs.model.DetailBon',
        'testextjs.model.Reglement',
        'testextjs.view.sm_user.factureregle.FactureRegleManager',
        // 'testextjs.view.sms_user.facturation.action.add'

        //Report
        'testextjs.view.Report.statistiquefamillearticle.statistiquefamillearticlemanager',
        'testextjs.model.Statistiquefamille',
//        'testextjs.view.Report.statistiquevente.statistiqueventemanager',

        'testextjs.model.Statistiquevente',
        'testextjs.model.Statistiqueunitevendue',

        'testextjs.view.stockmanagement.suivistockvente.action.detailArticle',
        'testextjs.view.sm_user.caisse.action.DoBilletage',
        'testextjs.view.stockmanagement.suivistockvente.action.detailArticle',
        'testextjs.model.Mouvement',
        'testextjs.model.Journaldesventes',
        'testextjs.view.Report.journaldesventes.journaldesventesmanager',
        'testextjs.view.Report.analyseFrequentationOff.analyseFrequentationOffManager',
        'testextjs.model.AnalyseFrequentationOff',
        'testextjs.model.ListeDiffereClient',
        'testextjs.view.Report.listeDiffereClient.listeDiffereClientManager',
        'testextjs.view.Report.statActiviteOperateur.statActiviteOperateurManager',
        'testextjs.model.StatActiviteOperateur',

        'testextjs.model.TableauBordPharmacien',
        'testextjs.model.ComparaisonChiffreAffaire',
        'testextjs.view.Report.DossierEnAttenteEdition.DossierEnAttenteEditionManager',
        'testextjs.model.DossierEnAttenteEdition',
        'testextjs.view.Report.AbandonEtAnnulation.AbandonEtAnnulationManager',
        'testextjs.model.AbandonEtAnnulation',
        'testextjs.view.Report.ListeDeCaisseDetaille.ListeDeCaisseDetailleManager',
        'testextjs.model.ListeDeCaisseDetaille',
        'testextjs.model.BalanceVenteCaisse',
        'testextjs.view.Report.BalanceAgeDetaille.BalanceAgeDetailleManager',
        'testextjs.model.BalanceAgeDetaille',
        'testextjs.view.Report.BalanceAgeOrganisme.BalanceAgeOrganismeManager',
        'testextjs.model.BalanceAgeOrganisme',
        'testextjs.model.BalanceAgeGenerale',
        //emplacement
        'testextjs.view.configmanagement.emplacement.EmplacementManager',
        'testextjs.model.Emplacement',
        'testextjs.view.configmanagement.emplacement.action.add',
        //fin emplacement


        //suivi mouvement article
        'testextjs.view.stockmanagement.suivistockvente.action.detailVente',
        'testextjs.view.stockmanagement.suivistockvente.action.detailRetour',
        'testextjs.view.stockmanagement.suivistockvente.action.detailPerime',
        'testextjs.view.stockmanagement.suivistockvente.action.detailEntree',
        'testextjs.view.stockmanagement.suivistockvente.action.detailCommande',
        'testextjs.view.stockmanagement.suivistockvente.action.detailStock',
        //code tva
        'testextjs.model.CodeTva',
        'testextjs.model.BalanceAgee',
        'testextjs.view.sm_user.mvtcaisse.MvtCaisseManager',
        'testextjs.model.MvtCaisse',
        'testextjs.view.sm_user.mvtcaisse.action.add',
        'testextjs.model.TypeEcartMvt',
        'testextjs.view.configmanagement.client.action.addClientLast',
        'testextjs.view.sm_user.dovente.action.associateTiersPayantItem',
        'testextjs.view.sm_user.parameter.ParameterManager',
        'testextjs.view.sm_user.parameter.action.add',
        'testextjs.model.Parameter',
        'testextjs.view.configmanagement.parametreGeneraux.ParametreGenerauxManager',
        'testextjs.view.configmanagement.parametreGeneraux.action.maxVente',
        'testextjs.model.Dci_famille',
        //ajustement
        'testextjs.model.Ajustement',
//        'testextjs.view.stockmanagement.ajustementmanagement.ajustementManager',
//        'testextjs.view.stockmanagement.ajustementmanagement.action.add',
        'testextjs.model.DetailsAjustement',
//        'testextjs.view.stockmanagement.ajustementmanagement.action.detailAjustement',
        'testextjs.view.stockmanagement.suivistockvente.action.detailOther',
        //fin ajustement

//suite commmande
        'testextjs.view.commandemanagement.order.action.importOrder',
        //gestion des imprimantes
        'testextjs.view.configmanagement.imprimantemanager.ImprimanteManager',
        'testextjs.model.Imprimante',
        'testextjs.view.configmanagement.imprimantemanager.action.add',
        'testextjs.view.configmanagement.famille.ArticleVendu',
        'testextjs.view.sm_user.user.action.addPrinter',
        'testextjs.view.sm_user.user.action.addUserPhone',
        'testextjs.view.sm_user.info_officine.OfficineManager',
        'testextjs.model.Officine',

        'testextjs.view.sm_user.mouvementprix.Mouvementprixvente',
        'testextjs.view.configmanagement.famille.action.add2',
        'testextjs.view.stockmanagement.suivistockvente.action.detailAjustement',
        'testextjs.view.stockmanagement.suivistockvente.action.detailInventaire',

        'testextjs.view.configmanagement.famille.action.export',
        'testextjs.model.ModelFacture',
        'testextjs.view.stockmanagement.retourdepot.retourdepotManager',
        'testextjs.view.stockmanagement.retourdepot.action.add',
        'testextjs.view.sm_user.journalvente.action.detailProduct',
        //Martial
        'testextjs.model.SnapshotFamille',
        'testextjs.view.sm_user.journalvente.FactureSubrogatoireManager',
        'testextjs.view.sm_user.privilege.action.add',
        'testextjs.model.Devise',
        'testextjs.view.configmanagement.devise.DeviseManager',
        'testextjs.view.configmanagement.devise.action.add',
        'testextjs.view.tierspayantmanagement.tierspayant.TiersPayantDesactiveManager',
        'testextjs.view.configmanagement.client.ClientDesactiveManager',
        'testextjs.view.sm_user.journalvente.FactureSubrogatoireBisManager',
        'testextjs.view.stockmanagement.dodepot.action.importOrder',
        'testextjs.view.stockmanagement.etiquette.action.addBis',
        'testextjs.view.configmanagement.famille.action.detailArticleOther',
        'testextjs.view.sm_user.reglement.FactureenAttendeEditionManager',
        'testextjs.view.sm_user.vente.VenteManagerBis',
        'testextjs.view.sm_user.vente.action.add',
        'testextjs.view.configmanagement.famille.action.updatezonegeo',
        'testextjs.view.stockmanagement.etatstock.action.removeLot',
        'testextjs.view.sm_user.outboudmessage.action.add',
        'testextjs.view.configmanagement.zonegeographique.action.changeProduitEmplacement',

        'testextjs.view.sm_user.mvtcaisse.MvtCaisseBisManager',
        'testextjs.view.sm_user.mvtcaisse.action.addBis',
        'testextjs.view.sm_user.vente.VendeurCaissierManager',
        'testextjs.view.commandemanagement.evaluation.Evaluationoffreprix',
        'testextjs.view.commandemanagement.evaluation.action.add',
        'testextjs.view.configmanagement.famille.ArticleVenduBis',
        'testextjs.view.commandemanagement.retourfournisseur.action.reponseretourfournisseur',
        //fin Martial

        'testextjs.view.configmanagement.famille.action.importOrder',
        'testextjs.view.Report.statistiquevente.SalesStatistcManager',
        /* kobena 14 01 2016 */
        'testextjs.view.Report.comparaisonCAFamilles.CAFamilleManager',
        'testextjs.view.Report.RuptureStock.RuptureStockManager',
        'testextjs.view.Report.analyseventestock.analyseventestockmanager',
        'testextjs.view.Report.AchatsFournisseurs.AchatFournisseursManager',
        'testextjs.view.Report.achatproduits.AchatProduitManager',
        'testextjs.view.Report.venteavoirclient.venteavoirclientkmanager',
        'testextjs.view.Report.ventesocietereglement.ventesocietereglementManager',
        'testextjs.view.Report.Retrocessions.RetrocessionsManager',
        'testextjs.view.commandemanagement.lots.LotsManager',
        'testextjs.view.Report.RapportGestions.RapportGestionsManager',
        'testextjs.view.sm_user.Defferedpaiement.DefferedPaiement',
        'testextjs.view.sm_user.RecapOrganisme.RecapManager',
        'testextjs.view.sm_user.Defferedpaiement.action.add',
        'testextjs.model.ReferenceVente',
        'testextjs.model.StatistiqueMois',
        'testextjs.model.Vente',
        'testextjs.view.tierspayantmanagement.tierspayant.action.detailstierspayant',
        'testextjs.view.configmanagement.litige.action.add',
        'testextjs.view.commandemanagement.etats.action.quinzaineManager',
        'testextjs.view.commandemanagement.etats.action.paybls',
        'testextjs.view.commandemanagement.etats.action.addQuinzaine',
        'testextjs.store.Lot',
        'testextjs.model.Quinzaine',
        'testextjs.view.configmanagement.famille.action.detailArticleVendus',
        'testextjs.view.Report.saisieperimes.SaisiePerimeManager',
        /* 0603207 */
        'testextjs.view.configmanagement.categoryclient.CategoryClientManger',
        'testextjs.view.Report.uniteGratuite.UniteGratuite',
        'testextjs.view.tierspayantmanagement.groupetierspayant.groupe',
        'testextjs.view.tierspayantmanagement.groupetierspayant.groupeInvoices',
        'testextjs.view.Report.statqties.qtymanager',
        'testextjs.view.Report.statsAchats.statsAchats',
        'testextjs.view.Report.activities.rapportactivite',
        'testextjs.view.stockmanagement.valorisation.Valorisation',
        'testextjs.view.configmanagement.logfile.logManager',
        'testextjs.view.configmanagement.company.company',
        'testextjs.view.actions.Doublons',
        'testextjs.view.caisseManager.TicketzManager',
        'testextjs.view.sm_user.ventecaisse.VentecaisseManager',
        'testextjs.view.Report.resultatstva.TvaManager',
        'testextjs.view.sm_user.vente.VenteHistoriqueDepotManager',
//        'testextjs.view.Report.TableauBordPharmacien.tableauBordPharmacienManager',
        'testextjs.view.produits.mvtproduit.*',

//        'testextjs.view.actions.Balance',
//        'testextjs.view.actions.TvaManager',
//        'testextjs.view.sm_user.listecaisse.ListeCaisseManager'
//        'testextjs.view.sm_user.visualisercaisse.VisualiserCaisseManager',

        // Devis
//        'testextjs.view.sm_user.devis.DevisManager',
        // Entré en stock
//        , 'testextjs.view.sm_user.balancevente.Balanceventemanager',
//        'testextjs.view.Report.BalanceVenteCaisse.BalanceVenteCaisseManager',
        'testextjs.view.facturation.ModelFacture',
        'testextjs.view.facturation.FactureProvisoire',
        'testextjs.view.caisseManager.Importation',
        'testextjs.view.actions.action',
        'testextjs.view.configmanagement.famille.Products',
        'testextjs.view.depot.Export',
        'testextjs.view.depot.Import',
        'testextjs.view.depot.Export'


// 'testextjs.view.sm_user.gestcaisse.GestCaisseManager',

//'testextjs.view.configmanagement.famille.FamilleStockComparaisonManager'
    ],
    controllers: [
        'App',
        'VisualisationCtr',
        'ListeCaisseCtr',
        'VenteCtr',
        'PendingCtr',
        'PreVentesCtr',
        'ProduitDesactivesCtr',
        'DevisListCtr',
        'DevisCtr',
        'DepotListCtr',
        'DepotCtr',
        'AnnulationCtr',
        'VenteFinisCtr',
        'ListeAvoirCtr',
        'AvoirCtr',
        'AjusteListCtr',
        'AjustementCtr',
        'BalanceVenteCtr',
        'GestionCaisseCtr',
        'TableauBoardCtr',
        'TvaCtr',
        'ReportCtr',
        'MvtArticleCtr',
        'DiffereCtr',
        'FaireReglementCtr',
        'DashBoardCtr',
        'RecapCtr',
        'FactureCtr',
        'FamilleArticleStatsCtr',
        'VingthManagerCtr',
        'peremptionManagerCtr',
        'MargeManagerCtr',
        'UnitesVenduesCtr',
        'RupturepharmaCtr',
        'GroupeGrossisteCtr',
        'GammeProduitCtr',
        'LaboratoireCtr',
        'StatsByGammeCtr',
        'StatsByLaboratoireCtr',
        'CashmovementCtr',
        'StatistiqProviderCtr',
        'StatistiqRayonsCtr',
        'ArticleInvendusCtr',
        'SurStockCtr',
        'ComparaisonCtr',
        'OrdonnancierCtrl',
        'VenteTiersPayantsCtr',
        'UgCtr',
        'ImportationHistoriqueCtr',
        'ParaCtr'
    ],
    stores: [
        'Menu'
    ],
    autoCreateViewport: true

});
