Ext.define('testextjs.model.statistics.FamilleCA', {
    extend: 'Ext.data.Model',
    idProperty: 'id',
    fields: [
        {name: 'id', type: 'string'},
        {name: 'GP', type: 'string'},
        {name: 'janvier_1',type: 'float'},
        {name: 'P_janvier_1'},
        {name: 'janvier',type: 'float'},
        {name: 'P_janvier'},
        {name: 'fevrier_1',type: 'float'},
        {name: 'P_fevrier_1'},
        {name: 'fevrier',type: 'float'},
        {name: 'P_fevrier'},
        {name: 'mars_1',type: 'float'},
        {name: 'P_mars_1'},
        {name: 'mars',type: 'float'},
        {name: 'P_mars'},
        {name: 'Prog_mars'},
        {name: 'Prog_fevrier'},
        {name: 'Prog_janvier'},
        {name: 'avril_1',type: 'float'},
        {name: 'P_avril_1'},
        {name: 'avril',type: 'float'},
        {name: 'P_avril'},
        {name: 'Prog_avril'},
        {name: 'mai_1',type: 'float'},
        {name: 'P_mai_1'},
        {name: 'mai',type: 'float'},
        {name: 'P_mai'},
        {name: 'Prog_mai'},
        {name: 'juin_1',type: 'float'},
        {name: 'P_juin_1'},
        {name: 'juin',type: 'float'},
        {name: 'P_juin'},
        {name: 'Prog_juin'},
        {name: 'juillet_1',type: 'float'},
        {name: 'P_juillet_1'},
        {name: 'juillet',type: 'float'},
        {name: 'P_juillet'},
        {name: 'Prog_juillet'},
        {name: 'aout_1',type: 'float'},
        {name: 'P_aout_1'},
        {name: 'aout',type: 'float'},
        {name: 'P_aout'},
        {name: 'Prog_aout'},
        {name: 'sep_1',type: 'float'},
        {name: 'P_sep_1'},
        {name: 'sep',type: 'float'},
        {name: 'P_sep'},
        {name: 'Prog_sep'},
        {name: 'oct_1',type: 'float'},
        {name: 'P_oct_1'},
        {name: 'oct',type: 'float'},
        {name: 'P_oct'},
        {name: 'Prog_oct'},
        {name: 'nov_1',type: 'float'},
        {name: 'P_nov_1'},
        {name: 'nov',type: 'float'},
        {name: 'P_nov'},
        {name: 'Prog_nov'},
        {name: 'dec_1',type: 'float'},
        {name: 'P_dec_1'},
        {name: 'dec',type: 'float'},
        {name: 'P_dec'},
        {name: 'Prog_dec'},
        {name: 'str_Libelle_Produit', type: 'string'}

    ]
});

