SET GLOBAL event_scheduler = ON;
CREATE TABLE IF NOT EXISTS `date_ouverture` (
		`id` INT(11) NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME NOT NULL,
	`mvtDate` DATE NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
DELIMITER @@
CREATE OR REPLACE EVENT  `EVERY_DAY_JOB` 
ON SCHEDULE EVERY 1 DAY 
 ON COMPLETION PRESERVE
DO BEGIN
INSERT INTO date_ouverture (`created_at`,`mvtDate`) VALUES(CURRENT_TIMESTAMP(),CURDATE());	
END @@ 
DELIMITER ; 