ALTER TABLE t_facture ADD COLUMN `type_facture` INT(3) NULL DEFAULT NULL;
ALTER TABLE t_facture ADD COLUMN `type_facture_id` VARCHAR(50) NULL DEFAULT NULL;
ALTER TABLE t_facture ADD COLUMN `groupeTp_id` MEDIUMINT(9) NULL DEFAULT NULL;
