INSERT IGNORE INTO t_parameters (`str_KEY`, `str_VALUE`, `str_DESCRIPTION`, `str_TYPE`, `str_STATUT`, `str_IS_EN_KRYPTED`, `str_SECTION_KEY`, `dt_CREATED`, `dt_UPDATED`) 
	VALUES ('KEY_GERE_ORDONCIER', '0', 'PARAMETRE ACTIVATION GESTION ORDONNANCIER', 'CUSTOMER', 'enable', NULL, NULL, NULL, NULL);
