
INSERT IGNORE INTO t_privilege (`lg_PRIVELEGE_ID`, `str_NAME`, `str_TYPE`, `str_DESCRIPTION`, `lg_PRIVELEGE_ID_DEP`, `dt_CREATED`, `lg_CREATED_BY`, `dt_UPDATED`, `lg_UPDATED_BY`, `str_STATUT`) 
	VALUES ('01102020', 'P_BTN_UPDATE_VENTE_CLIENT_TP', 'CUSTOMER', 'MODIFICATION TP/CLIENT VENTE A CREDIT', NULL, NULL, NULL, NULL, NULL, 'enable');
