INSERT IGNORE INTO t_parameters (`str_KEY`, `str_VALUE`, `str_DESCRIPTION`, `str_TYPE`, `str_STATUT`, `str_IS_EN_KRYPTED`, `str_SECTION_KEY`, `dt_CREATED`, `dt_UPDATED`) 
	VALUES ('AFFICHER_STOCK', '0', 'AFFICHE LE STOCK A LA VALEUR 1', 'CUSTOMER', 'enable', NULL, NULL, '2016-11-23 17:10:03.0', '2016-11-23 17:10:04.0');

