UPDATE t_parameters SET `str_VALUE` = '0' WHERE `str_KEY` = 'KEY_PARAMS';
UPDATE t_parameters SET `str_VALUE` = '0' WHERE `str_KEY` = 'KEY_TAKE_INTO_ACCOUNT';
INSERT IGNORE INTO t_parameters (`str_KEY`, `str_VALUE`, `str_DESCRIPTION`, `str_TYPE`, `str_STATUT`, `str_IS_EN_KRYPTED`, `str_SECTION_KEY`, `dt_CREATED`, `dt_UPDATED`) 
	VALUES ('KEY_PRENDRE_EN_COMPTE_FOND_CAISSE', '0', 'PRENDRE EN COMPTE LE FOND DE CAISSE DANS LE CALCUL DE LA RECETTE', 'CUSTOMER', 'enable', NULL, NULL, NULL, NULL);
