ALTER TABLE hmvtproduit  ADD COLUMN IF NOT EXISTS lg_PREENREGISTREMENT_DETAIL_ID   VARCHAR(40) NULL DEFAULT NULL;
ALTER TABLE hmvtproduit ADD  CONSTRAINT  `FKtkq9ekafqys2agl9afxhh92yb` FOREIGN KEY  IF NOT EXISTS (`lg_PREENREGISTREMENT_DETAIL_ID`)  REFERENCES `t_preenregistrement_detail` (`lg_PREENREGISTREMENT_DETAIL_ID`);
