
	INSERT IGNORE  INTO t_sous_menu (`lg_SOUS_MENU_ID`, `str_VALUE`, 
`str_IMAGE_CSS`, `str_DESCRIPTION`, `str_COMPOSANT`, `lg_MENU_ID`, 
`int_PRIORITY`, `str_URL`, `str_Status`, `P_KEY`, `dt_CREATED`, `dt_UPDATED`,
 `icon_CLASS`) 
	VALUES ('202312112051', 'PRODUITS ANNULES EN INVENTAIRE', NULL, 'LISTE DES PRODUITS ANNULES EN INVENTAIRE', 'venteproduitannules', '55111546114940284023', 10, NULL, 'enable', 'P_SM_INVENTAIRE_PRODUIT_ANNULES', NULL, NULL, '');

INSERT IGNORE  INTO t_privilege (`lg_PRIVELEGE_ID`, `str_NAME`, `str_TYPE`, `str_DESCRIPTION`, `lg_PRIVELEGE_ID_DEP`, `dt_CREATED`, `lg_CREATED_BY`, `dt_UPDATED`, `lg_UPDATED_BY`, `str_STATUT`) 
	VALUES ('202312112051', 'P_SM_INVENTAIRE_PRODUIT_ANNULES', 'CUSTOMER', ' LISTE DES PRODUITS ANNULES EN INVENTAIRE', NULL, NOW(), NULL, NULL, NULL, 'enable');

