
	INSERT IGNORE  INTO t_sous_menu (`lg_SOUS_MENU_ID`, `str_VALUE`, 
`str_IMAGE_CSS`, `str_DESCRIPTION`, `str_COMPOSANT`, `lg_MENU_ID`, 
`int_PRIORITY`, `str_URL`, `str_Status`, `P_KEY`, `dt_CREATED`, `dt_UPDATED`,
 `icon_CLASS`) 
	VALUES ('20230910', 'STATISTIQUE ANNUEL DES ACHATS', NULL, 'STATISTIQUE ANNUEL DES ACHATS', 'achatannuel', '3', 10, NULL, 'enable', 'P_SM_ETAT_ACHAT_ANNUEL', NULL, NULL, '');

INSERT IGNORE  INTO t_privilege (`lg_PRIVELEGE_ID`, `str_NAME`, `str_TYPE`, `str_DESCRIPTION`, `lg_PRIVELEGE_ID_DEP`, `dt_CREATED`, `lg_CREATED_BY`, `dt_UPDATED`, `lg_UPDATED_BY`, `str_STATUT`) 
	VALUES ('20230910', 'P_SM_ETAT_ACHAT_ANNUEL', 'CUSTOMER', 'STATISTIQUE ANNUEL DES ACHATS', NULL, NOW(), NULL, NULL, NULL, 'enable');



	INSERT IGNORE  INTO t_sous_menu (`lg_SOUS_MENU_ID`, `str_VALUE`, 
`str_IMAGE_CSS`, `str_DESCRIPTION`, `str_COMPOSANT`, `lg_MENU_ID`, 
`int_PRIORITY`, `str_URL`, `str_Status`, `P_KEY`, `dt_CREATED`, `dt_UPDATED`,
 `icon_CLASS`) 
	VALUES ('202309100', 'STATISTIQUE ANNUEL CA', NULL, 'STATISTIQUE ANNUEL CA', 'caannuel', '3', 10, NULL, 'enable', 'P_SM_ETAT_CA_ANNUEL', NULL, NULL, '');

INSERT IGNORE  INTO t_privilege (`lg_PRIVELEGE_ID`, `str_NAME`, `str_TYPE`, `str_DESCRIPTION`, `lg_PRIVELEGE_ID_DEP`, `dt_CREATED`, `lg_CREATED_BY`, `dt_UPDATED`, `lg_UPDATED_BY`, `str_STATUT`) 
	VALUES ('202309100', 'P_SM_ETAT_CA_ANNUEL', 'CUSTOMER', 'STATISTIQUE ANNUEL CA', NULL, NOW(), NULL, NULL, NULL, 'enable');

