
INSERT IGNORE INTO t_parameters (`str_KEY`, `str_VALUE`, `str_DESCRIPTION`, `str_TYPE`, `str_STATUT`, `str_IS_EN_KRYPTED`, `str_SECTION_KEY`, `dt_CREATED`, `dt_UPDATED`) 
	VALUES ('KEY_OPTION_SUGGESTION', '<', 'OPTION DE SUGGESTION: CAS 1: “<“ STOCK EST STRICTEMENT INFÉRIEUR AU SEUIL CAS 2:  “<=” STOCK EST INFÉRIEUR OU ÉGAL AU SEUIL CAS 3: “=” STOCK EST ÉGAL AU SEUIL', 'CUSTOMER', 'enable', NULL, NULL, NOW(), NOW());
