CREATE TABLE IF NOT EXISTS `t_mouvement_reserve` (
	`lg_MOUVEMENT_ID` VARCHAR(40) NOT NULL COLLATE 'utf8_general_ci',
	`lg_FAMILLE_ID` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`lg_USER_ID` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`lg_EMPLACEMENT_ID` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`str_TYPE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`int_QTE` INT(11) NULL DEFAULT NULL,
	`int_STOCK_RAYON_AVANT` INT(11) NULL DEFAULT NULL,
	`int_STOCK_RESERVE_AVANT` INT(11) NULL DEFAULT NULL,
	`int_STOCK_RAYON_APRES` INT(11) NULL DEFAULT NULL,
	`int_STOCK_RESERVE_APRES` INT(11) NULL DEFAULT NULL,
	`dt_CREATED` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`lg_MOUVEMENT_ID`) USING BTREE,
	INDEX `idx_mvt_reserve_famille` (`lg_FAMILLE_ID`) USING BTREE,
	INDEX `idx_mvt_reserve_date` (`dt_CREATED`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;