-- =====================================================================
-- Centre de Support - Veilleur de coherence : enrichissement du contexte
-- ---------------------------------------------------------------------
-- La 2e colonne (contexte) de chaque controle renvoie desormais un repere
-- PARLANT (n de reference, date, nom du client / de l'article, statut) au
-- lieu du statut brut, pour retrouver immediatement l'enregistrement.
-- Requetes toujours en LECTURE SEULE ; colonnes verifiees sur les entites.
-- Seule la colonne de contexte (et les LEFT JOIN d'affichage) change ; la
-- logique de detection (WHERE) est identique.
-- =====================================================================

UPDATE t_support_controle SET requete_sql = 'SELECT b.lg_BON_LIVRAISON_ID AS id, CONCAT(''BL '', COALESCE(b.str_REF_LIVRAISON,''?''), '' du '', COALESCE(DATE(b.dt_DATE_LIVRAISON),''?''), '' ['', b.str_STATUT, '']'') AS ctx FROM t_bon_livraison b LEFT JOIN t_bon_livraison_detail d ON d.lg_BON_LIVRAISON_ID = b.lg_BON_LIVRAISON_ID WHERE b.str_STATUT IN (''enable'',''is_Closed'') AND d.lg_BON_LIVRAISON_DETAIL IS NULL', modified_at = NOW() WHERE code = 'BL_SANS_DETAIL';

UPDATE t_support_controle SET requete_sql = 'SELECT f.lg_FACTURE_ID AS id, CONCAT(''Facture '', COALESCE(f.str_CODE_FACTURE,''?''), '' du '', COALESCE(DATE(f.dt_DATE_FACTURE),''?''), '' ['', f.str_STATUT, '']'') AS ctx FROM t_facture f LEFT JOIN t_facture_detail d ON d.lg_FACTURE_ID = f.lg_FACTURE_ID AND d.str_STATUT <> ''delete'' WHERE f.str_STATUT <> ''delete'' AND f.template = 0 AND d.lg_FACTURE_DETAIL_ID IS NULL', modified_at = NOW() WHERE code = 'FACTURE_SANS_DETAIL';

UPDATE t_support_controle SET requete_sql = 'SELECT s.lg_SUGGESTION_ORDER_ID AS id, CONCAT(''Suggestion '', COALESCE(s.str_REF,''?''), '' ['', s.str_STATUT, '']'') AS ctx FROM t_suggestion_order s LEFT JOIN t_suggestion_order_details d ON d.lg_SUGGESTION_ORDER_ID = s.lg_SUGGESTION_ORDER_ID AND d.str_STATUT <> ''delete'' WHERE s.str_STATUT <> ''delete'' AND d.lg_SUGGESTION_ORDER_DETAILS_ID IS NULL', modified_at = NOW() WHERE code = 'SUGGESTION_SANS_DETAIL';

UPDATE t_support_controle SET requete_sql = 'SELECT o.lg_ORDER_ID AS id, CONCAT(''Commande '', COALESCE(o.str_REF_ORDER,''?''), '' ['', o.str_STATUT, '']'') AS ctx FROM t_order o LEFT JOIN t_order_detail d ON d.lg_ORDER_ID = o.lg_ORDER_ID AND d.str_STATUT <> ''delete'' WHERE d.lg_ORDERDETAIL_ID IS NULL', modified_at = NOW() WHERE code = 'COMMANDE_SANS_DETAIL';

UPDATE t_support_controle SET requete_sql = 'SELECT dr.lg_DOSSIER_REGLEMENT_ID AS id, CONCAT(''Dossier '', COALESCE(dr.str_NATURE_DOSSIER,''?''), '' ['', dr.str_STATUT, '']'') AS ctx FROM t_dossier_reglement dr LEFT JOIN t_dossier_reglement_detail d ON d.lg_DOSSIER_REGLEMENT_ID = dr.lg_DOSSIER_REGLEMENT_ID WHERE dr.str_STATUT <> ''delete'' AND d.lg_DOSSIER_REGLEMENT_DETAIL_ID IS NULL', modified_at = NOW() WHERE code = 'DOSSIER_REGLEMENT_SANS_DETAIL';

UPDATE t_support_controle SET requete_sql = 'SELECT p.lg_PREENREGISTREMENT_ID AS id, CONCAT(''Vente du '', COALESCE(p.completion_date,''?''), '' - '', COALESCE(cli.str_FIRST_NAME,''''), '' '', COALESCE(cli.str_LAST_NAME,'''')) AS ctx FROM t_preenregistrement p LEFT JOIN t_client cli ON cli.lg_CLIENT_ID = p.lg_CLIENT_ID WHERE p.str_STATUT = ''is_Closed'' AND p.lg_TYPE_VENTE_ID = ''1'' AND (p.b_IS_CANCEL IS NULL OR p.b_IS_CANCEL = 0) AND p.lg_PREENGISTREMENT_ANNULE_ID IS NULL AND p.lg_PARENT_ID IS NULL AND p.completion_date >= (NOW() - INTERVAL 48 HOUR) AND NOT EXISTS (SELECT 1 FROM MvtTransaction m WHERE m.vente_id = p.lg_PREENREGISTREMENT_ID OR m.pkey = p.lg_PREENREGISTREMENT_ID)', modified_at = NOW() WHERE code = 'VENTE_COMPTANT_SANS_MVT_CAISSE';

UPDATE t_support_controle SET requete_sql = 'SELECT p.lg_PREENREGISTREMENT_ID AS id, CONCAT(''Vente du '', COALESCE(p.completion_date,''?''), '' - '', COALESCE(cli.str_FIRST_NAME,''''), '' '', COALESCE(cli.str_LAST_NAME,'''')) AS ctx FROM t_preenregistrement p LEFT JOIN t_client cli ON cli.lg_CLIENT_ID = p.lg_CLIENT_ID WHERE p.str_STATUT = ''is_Closed'' AND p.lg_TYPE_VENTE_ID = ''1'' AND (p.b_IS_CANCEL IS NULL OR p.b_IS_CANCEL = 0) AND p.lg_PREENGISTREMENT_ANNULE_ID IS NULL AND p.lg_PARENT_ID IS NULL AND p.completion_date >= (NOW() - INTERVAL 48 HOUR) AND EXISTS (SELECT 1 FROM t_preenregistrement_detail d WHERE d.lg_PREENREGISTREMENT_ID = p.lg_PREENREGISTREMENT_ID) AND NOT EXISTS (SELECT 1 FROM t_preenregistrement_detail d JOIN HMvtProduit h ON h.lg_PREENREGISTREMENT_DETAIL_ID = d.lg_PREENREGISTREMENT_DETAIL_ID WHERE d.lg_PREENREGISTREMENT_ID = p.lg_PREENREGISTREMENT_ID)', modified_at = NOW() WHERE code = 'VENTE_COMPTANT_SANS_MVT_STOCK';

UPDATE t_support_controle SET requete_sql = 'SELECT p.lg_PREENREGISTREMENT_ID AS id, CONCAT(''vente: '', COALESCE(cliv.str_FIRST_NAME,''''), '' '', COALESCE(cliv.str_LAST_NAME,''''), '' | compte de: '', COALESCE(clic.str_FIRST_NAME,''''), '' '', COALESCE(clic.str_LAST_NAME,'''')) AS ctx FROM t_preenregistrement p JOIN t_preenregistrement_compte_client pcc ON pcc.lg_PREENREGISTREMENT_ID = p.lg_PREENREGISTREMENT_ID JOIN t_compte_client cc ON cc.lg_COMPTE_CLIENT_ID = pcc.lg_COMPTE_CLIENT_ID LEFT JOIN t_ayant_droit ad ON ad.lg_AYANTS_DROITS_ID = p.lg_AYANTS_DROITS_ID LEFT JOIN t_client cliv ON cliv.lg_CLIENT_ID = p.lg_CLIENT_ID LEFT JOIN t_client clic ON clic.lg_CLIENT_ID = cc.lg_CLIENT_ID WHERE p.str_STATUT_VENTE = ''Differe'' AND (p.b_IS_CANCEL IS NULL OR p.b_IS_CANCEL = 0) AND cc.lg_CLIENT_ID <> p.lg_CLIENT_ID AND (ad.lg_CLIENT_ID IS NULL OR cc.lg_CLIENT_ID <> ad.lg_CLIENT_ID)', modified_at = NOW() WHERE code = 'DIFFERE_MAUVAIS_COMPTE';

UPDATE t_support_controle SET requete_sql = 'SELECT p.lg_PREENREGISTREMENT_ID AS id, CONCAT(''vente: '', COALESCE(cliv.str_FIRST_NAME,''''), '' '', COALESCE(cliv.str_LAST_NAME,''''), '' | compte TP de: '', COALESCE(clic.str_FIRST_NAME,''''), '' '', COALESCE(clic.str_LAST_NAME,'''')) AS ctx FROM t_preenregistrement p JOIN t_preenregistrement_compte_client_tiers_payent pct ON pct.lg_PREENREGISTREMENT_ID = p.lg_PREENREGISTREMENT_ID JOIN t_compte_client_tiers_payant cctp ON cctp.lg_COMPTE_CLIENT_TIERS_PAYANT_ID = pct.lg_COMPTE_CLIENT_TIERS_PAYANT_ID JOIN t_compte_client cc ON cc.lg_COMPTE_CLIENT_ID = cctp.lg_COMPTE_CLIENT_ID LEFT JOIN t_ayant_droit ad ON ad.lg_AYANTS_DROITS_ID = p.lg_AYANTS_DROITS_ID LEFT JOIN t_client cliv ON cliv.lg_CLIENT_ID = p.lg_CLIENT_ID LEFT JOIN t_client clic ON clic.lg_CLIENT_ID = cc.lg_CLIENT_ID WHERE (p.b_IS_CANCEL IS NULL OR p.b_IS_CANCEL = 0) AND cc.lg_CLIENT_ID <> p.lg_CLIENT_ID AND (ad.lg_CLIENT_ID IS NULL OR cc.lg_CLIENT_ID <> ad.lg_CLIENT_ID)', modified_at = NOW() WHERE code = 'TIERS_PAYANT_MAUVAIS_COMPTE';

UPDATE t_support_controle SET requete_sql = 'SELECT i.lg_INVENTAIRE_ID AS id, CONCAT(COALESCE(i.str_NAME,''?''), '' ['', i.str_STATUT, '']'') AS ctx FROM t_inventaire i LEFT JOIN t_inventaire_famille f ON f.lg_INVENTAIRE_ID = i.lg_INVENTAIRE_ID WHERE i.str_STATUT IN (''enable'',''is_Closed'') AND f.lg_INVENTAIRE_FAMILLE_ID IS NULL', modified_at = NOW() WHERE code = 'INVENTAIRE_SANS_LIGNE';

UPDATE t_support_controle SET requete_sql = 'SELECT l.lg_LOT_ID AS id, CONCAT(''Lot '', COALESCE(l.int_NUM_LOT,''?''), '' - '', COALESCE(fam.str_NAME,''''), '' - perime le '', COALESCE(DATE(l.dt_PEREMPTION),''?''), '' - reste '', l.current_stock) AS ctx FROM t_lot l LEFT JOIN t_famille fam ON fam.lg_FAMILLE_ID = l.lg_FAMILLE_ID WHERE l.str_STATUT = ''perime'' AND l.current_stock > 0', modified_at = NOW() WHERE code = 'LOT_PERIME_AVEC_STOCK';

UPDATE t_support_controle SET requete_sql = 'SELECT l.lg_LOT_ID AS id, CONCAT(''Lot '', COALESCE(l.int_NUM_LOT,''?''), '' (article '', COALESCE(l.lg_FAMILLE_ID,''NULL''), '')'') AS ctx FROM t_lot l LEFT JOIN t_famille f ON f.lg_FAMILLE_ID = l.lg_FAMILLE_ID WHERE f.lg_FAMILLE_ID IS NULL', modified_at = NOW() WHERE code = 'LOT_SANS_ARTICLE';

UPDATE t_support_controle SET requete_sql = 'SELECT r.ld_CAISSE_ID AS id, CONCAT(''Caisse du '', COALESCE(DATE(r.dt_DAY),''?''), '' ['', r.str_STATUT, '']'') AS ctx FROM t_resume_caisse r LEFT JOIN ligne_resume_caisse lr ON lr.resume_caisse_id = r.ld_CAISSE_ID WHERE r.dt_DAY < CURDATE() AND lr.id IS NULL', modified_at = NOW() WHERE code = 'CAISSE_JOUR_SANS_LIGNE';

